Spherical Matrix
ACEsuit/ACE.jl pull request #24
Opened 2021-04-12 20:11 UTC by zhanglw0521

Spherical matrix implementation

2021-04-12 20:33 UTC, cortner requested changes
looks really good. But too much duplication now, let's get back to discussing how to unify everything. 

What about a `SphericalTensor`? Would that be any more difficult to write than what you already have?

2021-04-12 20:33 UTC, cortner commented on src/properties.jl
> +getL(φ::SphericalMatrix{L1,L2}) where {L1,L2} = [L1;L2]
please return a tuple here: `... where {L1, L2} = L1, L2`

* `[L1; L2]` is actually a matrix; to construct a vector use `[L1, L2]`. 
* Such a vector is allocating, whereas a tuple is on the stack. Further, the values `L1, L2` can be inferred if they are returned as a tuple.

2021-04-12 20:33 UTC, cortner commented on test/test_symmbasis.jl
> +      if L1 == 0
this is extremely ugly, why not define a function that gives you the symbol associated with each `L`? e.g., something along the lines of
```julia
const __L2syms = [:s, :p, :d, :f, :g, :h, :i, :k]
const __syms2L = Dict( [sym => L-1 for (L, sym) in enumerate(__L2syms)]... )
get_orbsym(L::Integer)  = __Lsyms[L+1]
get_L(sym::Union{AbstractString, Char, Symbol}) = __syms2L[ Symbol(sym) ]
```
should go somewhere inside the ACE module, not entirely sure yet where.

2021-04-12 20:33 UTC, cortner commented on test/test_symmbasis.jl
> +      if L1 == 0
and don't worry with the test numbers please

2021-04-12 20:33 UTC, cortner commented on test/test_symmbasis.jl
> +         Q, D1, D2 = ACE.Wigner.rand_QD(L1, L2)
* Can you please fix `rand_QD` to do the following: return an *orthogonal* matrix `Q` with the sign already integrated, and modified D-matrices `D1, D2` with the `(-1)^L1` already integrated into `D1`.

2021-04-12 20:33 UTC, cortner commented on test/test_symmbasis.jl
> +         Q, D1, D2 = ACE.Wigner.rand_QD(L1, L2)
So the usage should end up 
```julia
Q, D1, D2 = ACE.Wigner.rand_QD(L1, L2)
Xs1 = shuffle(Ref(Q) .* Xs)
D1txBB1xD2 = Ref(D1') .* BB1 .* Ref(D2)
```
I.e. no more `rand_ref`

2021-04-12 20:33 UTC, cortner commented on test/test_symmbasis.jl
> +         Q, D1, D2 = ACE.Wigner.rand_QD(L1, L2)
please fix this also in the other test

2021-04-13 18:57 UTC, cortner approved these changes

2021-04-13 22:01 UTC, cortner approved these changes

2021-04-13 22:01 UTC, cortner commented
looks great, thank you for your work on this.

2021-04-13 22:02 UTC, merged

2021-04-13 22:02 UTC, cortner commented
@zhanglw0521 I've squased those commits into a single one and to make sure you don't get clashes I've deleted your branch. You can restore it if you will, but best to pull and checkout `main` now and then create a new `lz/equiv` branch.

2021-04-13 22:08 UTC, zhanglw0521 commented
> @zhanglw0521 I've squased those commits into a single one and to make sure you don't get clashes I've deleted your branch. You can restore it if you will, but best to pull and checkout `main` now and then create a new `lz/equiv` branch.

Seems that I'd better create a new one - will just follow your suggestion. Thanks a lot!