N Body energy
ACEsuit/ACE.jl pull request #37
Opened 2021-05-26 15:35 UTC by davkovacs

Might not be the most elegant way of doing this, but I think it works. Takes a PIPotential, an Atoms object and a Body order as arguments and returns the contribution to the energy of the correct basis functions.

2021-05-26 18:23 UTC, cortner reviewed
to discuss later

2021-05-26 18:26 UTC, davkovacs commented on Project.toml
> +JuLIP = "0.11.2"
I had 0.11.2 on my machine, but nothing requires it. I should have removed that probably.

2021-05-26 18:26 UTC, davkovacs commented on src/utils/pure.jl
> +  IP_new = PIPotential(IP.pibasis, Cs)
Makes sense. I could do that.

2021-05-26 22:47 UTC, davkovacs commented
I have cleaned up according to our discussion, ready to merge (except for the JuLIP version part)

2021-06-01 04:10 UTC, cortner requested changes
I few more things. Sorry I'm slow. Too many things to take care of ...

2021-06-01 04:10 UTC, cortner commented on src/utils/pure.jl
> +  """
doc string goes in front of the function

2021-06-01 04:10 UTC, cortner commented on src/utils/pure.jl
> +  IP_new = PIPotential(IP.pibasis, Cs)
are you now duplicating code?  I think `nB_energy` should first call `nB_potential` to get the new model and then evaluate the new model.

2021-06-01 04:10 UTC, cortner commented on src/utils/pure.jl
> +  """
doc string in front of function

2021-06-01 10:02 UTC, davkovacs commented
Thank you for the feedback, and being patient, I am learning how to do all this, as I am doing these changes. I think I have changed everything as requested.

2021-06-06 04:27 UTC, merged

2021-06-06 04:27 UTC, cortner commented
sorry I dropped the ball on this.